# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Minust
    url: '#about'
    weight: 10
  - name: Teadussuunad
    url: '#research'
    weight: 20
  - name: Publikatsioonid
    url: '#publications'
    weight: 30
  - name: Tunnustused
    url: '#awards'
    weight: 40
  - name: Teenistuskäik
    url: '#employment'
    weight: 50
  - name: Ettekanded
    url: '#presentations'
    weight: 60
  - name: Kontakt
    url: '#contact'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: CV
    url: uploads/resume.pdf
    weight: 70
