# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Minust"
  url = "#about"
  weight = 10

[[main]]
  name = "Teadussuunad"
  url = "#research"
  weight = 20

[[main]]
  name = "Publikatsioonid"
  url = "#publications"
  weight = 30

[[main]]
  name = "Tunnustused"
  url = "#awards"
  weight = 40

[[main]]
  name = "Teenistuskäik"
  url = "#employment"
  weight = 50

[[main]]
  name = "Ettekanne"
  url = "#presentations"
  weight = 60

[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# TODO: make a PDF CV
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
